// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action.sql

package entities

import (
	"context"
	"encoding/json"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions (execution_id, task_id, tool_call, llm_response_id) VALUES (?, ?, ?, ?) RETURNING execution_id, task_id, llm_response_id, tool_call, tool_requirement_message_id, tool_result_message_id
`

type CreateActionParams struct {
	ExecutionID   string          `json:"execution_id"`
	TaskID        string          `json:"task_id"`
	ToolCall      json.RawMessage `json:"tool_call"`
	LlmResponseID string          `json:"llm_response_id"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction,
		arg.ExecutionID,
		arg.TaskID,
		arg.ToolCall,
		arg.LlmResponseID,
	)
	var i Action
	err := row.Scan(
		&i.ExecutionID,
		&i.TaskID,
		&i.LlmResponseID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}

const getAction = `-- name: GetAction :one
SELECT execution_id, task_id, llm_response_id, tool_call, tool_requirement_message_id, tool_result_message_id FROM actions WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetAction(ctx context.Context, executionID string) (Action, error) {
	row := q.db.QueryRowContext(ctx, getAction, executionID)
	var i Action
	err := row.Scan(
		&i.ExecutionID,
		&i.TaskID,
		&i.LlmResponseID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}

const updateActionMessages = `-- name: UpdateActionMessages :one
UPDATE actions 
SET tool_requirement_message_id = ?, tool_result_message_id = ? 
WHERE execution_id = ? RETURNING execution_id, task_id, llm_response_id, tool_call, tool_requirement_message_id, tool_result_message_id
`

type UpdateActionMessagesParams struct {
	ToolRequirementMessageID interface{} `json:"tool_requirement_message_id"`
	ToolResultMessageID      interface{} `json:"tool_result_message_id"`
	ExecutionID              string      `json:"execution_id"`
}

func (q *Queries) UpdateActionMessages(ctx context.Context, arg UpdateActionMessagesParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, updateActionMessages, arg.ToolRequirementMessageID, arg.ToolResultMessageID, arg.ExecutionID)
	var i Action
	err := row.Scan(
		&i.ExecutionID,
		&i.TaskID,
		&i.LlmResponseID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}
