// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package entities

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description) VALUES (?, ?) RETURNING name, description
`

type CreateChannelParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.Description)
	var i Channel
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT name, description FROM channels WHERE name = ? LIMIT 1
`

func (q *Queries) GetChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, name)
	var i Channel
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}

const getChannels = `-- name: GetChannels :many
SELECT name, description FROM channels
`

func (q *Queries) GetChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
