// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: complete_step.sql

package entities

import (
	"context"
)

const completeStep = `-- name: CompleteStep :one
UPDATE steps SET status = 'completed' WHERE id = ? RETURNING id, run_id, task_id, status, created_at
`

func (q *Queries) CompleteStep(ctx context.Context, id string) (Step, error) {
	row := q.db.QueryRowContext(ctx, completeStep, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
