// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: complete_run.sql

package entities

import (
	"context"
)

const completeRun = `-- name: CompleteRun :one
UPDATE runs SET status = 'completed' WHERE id = ? RETURNING id, mention_id, status, created_at
`

func (q *Queries) CompleteRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, completeRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
