// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_step.sql

package entities

import (
	"context"
)

const createStep = `-- name: CreateStep :one
INSERT INTO steps (id, run_id, kind) VALUES (?, ?, ?) RETURNING id, run_id, kind, created_at
`

type CreateStepParams struct {
	ID    string      `json:"id"`
	RunID interface{} `json:"run_id"`
	Kind  string      `json:"kind"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (Step, error) {
	row := q.db.QueryRowContext(ctx, createStep, arg.ID, arg.RunID, arg.Kind)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}
