// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_llm_response.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmResponse = `-- name: CreateLlmResponse :one
INSERT INTO llm_responses (id, step_id, task_id, openai_response) VALUES (?, ?, ?, ?) RETURNING id, step_id, task_id, openai_response, created_at
`

type CreateLlmResponseParams struct {
	ID             string          `json:"id"`
	StepID         string          `json:"step_id"`
	TaskID         string          `json:"task_id"`
	OpenaiResponse json.RawMessage `json:"openai_response"`
}

func (q *Queries) CreateLlmResponse(ctx context.Context, arg CreateLlmResponseParams) (LlmResponse, error) {
	row := q.db.QueryRowContext(ctx, createLlmResponse,
		arg.ID,
		arg.StepID,
		arg.TaskID,
		arg.OpenaiResponse,
	)
	var i LlmResponse
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.TaskID,
		&i.OpenaiResponse,
		&i.CreatedAt,
	)
	return i, err
}
