// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_llm_request.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmRequest = `-- name: CreateLlmRequest :one
INSERT INTO llm_requests (id, step_id, task_id, openai_request) VALUES (?, ?, ?, ?) RETURNING id, step_id, task_id, openai_request, created_at
`

type CreateLlmRequestParams struct {
	ID            string          `json:"id"`
	StepID        string          `json:"step_id"`
	TaskID        string          `json:"task_id"`
	OpenaiRequest json.RawMessage `json:"openai_request"`
}

func (q *Queries) CreateLlmRequest(ctx context.Context, arg CreateLlmRequestParams) (LlmRequest, error) {
	row := q.db.QueryRowContext(ctx, createLlmRequest,
		arg.ID,
		arg.StepID,
		arg.TaskID,
		arg.OpenaiRequest,
	)
	var i LlmRequest
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.TaskID,
		&i.OpenaiRequest,
		&i.CreatedAt,
	)
	return i, err
}
