// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_run.sql

package entities

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, kind) VALUES (?, ?) RETURNING id, kind, status, created_at
`

type CreateRunParams struct {
	ID   string `json:"id"`
	Kind string `json:"kind"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.ID, arg.Kind)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
