// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_handoff.sql

package entities

import (
	"context"
)

const createHandoff = `-- name: CreateHandoff :one
INSERT INTO handoffs (id, step_id, to_agent, tool_call_id) VALUES (?, ?, ?, ?) RETURNING id, step_id, to_agent, tool_call_id
`

type CreateHandoffParams struct {
	ID         string `json:"id"`
	StepID     string `json:"step_id"`
	ToAgent    string `json:"to_agent"`
	ToolCallID string `json:"tool_call_id"`
}

func (q *Queries) CreateHandoff(ctx context.Context, arg CreateHandoffParams) (Handoff, error) {
	row := q.db.QueryRowContext(ctx, createHandoff,
		arg.ID,
		arg.StepID,
		arg.ToAgent,
		arg.ToolCallID,
	)
	var i Handoff
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.ToAgent,
		&i.ToolCallID,
	)
	return i, err
}
