// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_action.sql

package entities

import (
	"context"
	"encoding/json"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions (id, step_id, tool_call_id, name, arguments) VALUES (?, ?, ?, ?, ?) RETURNING id, step_id, tool_call_id, name, arguments
`

type CreateActionParams struct {
	ID         string          `json:"id"`
	StepID     string          `json:"step_id"`
	ToolCallID string          `json:"tool_call_id"`
	Name       string          `json:"name"`
	Arguments  json.RawMessage `json:"arguments"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction,
		arg.ID,
		arg.StepID,
		arg.ToolCallID,
		arg.Name,
		arg.Arguments,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.ToolCallID,
		&i.Name,
		&i.Arguments,
	)
	return i, err
}
