// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_llm_chunk_response.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmChunkResponses = `-- name: CreateLlmChunkResponses :one
INSERT INTO llm_chunk_responses (id, sequence_number, step_id, task_id, openai_chunk_response) VALUES (?, ?, ?, ?, ?) RETURNING id, sequence_number, step_id, task_id, openai_chunk_response, created_at
`

type CreateLlmChunkResponsesParams struct {
	ID                  string          `json:"id"`
	SequenceNumber      int64           `json:"sequence_number"`
	StepID              string          `json:"step_id"`
	TaskID              string          `json:"task_id"`
	OpenaiChunkResponse json.RawMessage `json:"openai_chunk_response"`
}

func (q *Queries) CreateLlmChunkResponses(ctx context.Context, arg CreateLlmChunkResponsesParams) (LlmChunkResponse, error) {
	row := q.db.QueryRowContext(ctx, createLlmChunkResponses,
		arg.ID,
		arg.SequenceNumber,
		arg.StepID,
		arg.TaskID,
		arg.OpenaiChunkResponse,
	)
	var i LlmChunkResponse
	err := row.Scan(
		&i.ID,
		&i.SequenceNumber,
		&i.StepID,
		&i.TaskID,
		&i.OpenaiChunkResponse,
		&i.CreatedAt,
	)
	return i, err
}
