// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_channel.sql

package entities

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description) VALUES (?, ?) RETURNING name, description
`

type CreateChannelParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.Description)
	var i Channel
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}
