// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_tool.sql

package entities

import (
	"context"
	"encoding/json"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (id, task_id, name, description, parameters) VALUES (?, ?, ?, ?, ?) RETURNING id, task_id, name, description, parameters
`

type CreateToolParams struct {
	ID          string          `json:"id"`
	TaskID      string          `json:"task_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Parameters  json.RawMessage `json:"parameters"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRowContext(ctx, createTool,
		arg.ID,
		arg.TaskID,
		arg.Name,
		arg.Description,
		arg.Parameters,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.Description,
		&i.Parameters,
	)
	return i, err
}
