// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_action.sql

package entities

import (
	"context"
	"encoding/json"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions (id, run_id, step_id, tool_call_id, tool_call) VALUES (?, ?, ?, ?, ?) RETURNING id, run_id, step_id, tool_call_id, tool_call
`

type CreateActionParams struct {
	ID         string          `json:"id"`
	RunID      string          `json:"run_id"`
	StepID     string          `json:"step_id"`
	ToolCallID string          `json:"tool_call_id"`
	ToolCall   json.RawMessage `json:"tool_call"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction,
		arg.ID,
		arg.RunID,
		arg.StepID,
		arg.ToolCallID,
		arg.ToolCall,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.ToolCallID,
		&i.ToolCall,
	)
	return i, err
}
