// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_step_link.sql

package entities

import (
	"context"
	"database/sql"
)

const createStepLink = `-- name: CreateStepLink :one
INSERT INTO step_links (prev_id, next_id, linked_at) VALUES (?, ?, ?) RETURNING prev_id, next_id, linked_at
`

type CreateStepLinkParams struct {
	PrevID   string       `json:"prev_id"`
	NextID   string       `json:"next_id"`
	LinkedAt sql.NullTime `json:"linked_at"`
}

func (q *Queries) CreateStepLink(ctx context.Context, arg CreateStepLinkParams) (StepLink, error) {
	row := q.db.QueryRowContext(ctx, createStepLink, arg.PrevID, arg.NextID, arg.LinkedAt)
	var i StepLink
	err := row.Scan(&i.PrevID, &i.NextID, &i.LinkedAt)
	return i, err
}
