// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_message.sql

package entities

import (
	"context"
	"encoding/json"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, step_id, channel_name, role_id, task_id, visibility, openai_message) 
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, step_id, channel_name, role_id, task_id, visibility, openai_message, created_at
`

type CreateMessageParams struct {
	ID            string          `json:"id"`
	StepID        string          `json:"step_id"`
	ChannelName   string          `json:"channel_name"`
	RoleID        string          `json:"role_id"`
	TaskID        string          `json:"task_id"`
	Visibility    string          `json:"visibility"`
	OpenaiMessage json.RawMessage `json:"openai_message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.StepID,
		arg.ChannelName,
		arg.RoleID,
		arg.TaskID,
		arg.Visibility,
		arg.OpenaiMessage,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.ChannelName,
		&i.RoleID,
		&i.TaskID,
		&i.Visibility,
		&i.OpenaiMessage,
		&i.CreatedAt,
	)
	return i, err
}
