// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_run.sql

package entities

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, mention_id) VALUES (?, ?) RETURNING id, mention_id, status, created_at
`

type CreateRunParams struct {
	ID        string `json:"id"`
	MentionID string `json:"mention_id"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.ID, arg.MentionID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
