// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_role.sql

package entities

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, member_name, channel_name) VALUES (?, ?, ?) RETURNING id, member_name, channel_name
`

type CreateRoleParams struct {
	ID          string `json:"id"`
	MemberName  string `json:"member_name"`
	ChannelName string `json:"channel_name"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.ID, arg.MemberName, arg.ChannelName)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}
