// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_member.sql

package entities

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (name, kind) VALUES (?, ?) RETURNING name, kind
`

type CreateMemberParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember, arg.Name, arg.Kind)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}
