// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_run.sql

package entities

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, source_step_id) VALUES (?, ?) RETURNING id, source_step_id, created_at
`

type CreateRunParams struct {
	ID           string `json:"id"`
	SourceStepID string `json:"source_step_id"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.ID, arg.SourceStepID)
	var i Run
	err := row.Scan(&i.ID, &i.SourceStepID, &i.CreatedAt)
	return i, err
}
