// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_tool.sql

package entities

import (
	"context"
	"encoding/json"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (id, task_id, tool) VALUES (?, ?, ?) RETURNING id, task_id, tool
`

type CreateToolParams struct {
	ID     string          `json:"id"`
	TaskID string          `json:"task_id"`
	Tool   json.RawMessage `json:"tool"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRowContext(ctx, createTool, arg.ID, arg.TaskID, arg.Tool)
	var i Tool
	err := row.Scan(&i.ID, &i.TaskID, &i.Tool)
	return i, err
}
