// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_mention.sql

package entities

import (
	"context"
)

const createMention = `-- name: CreateMention :one
INSERT INTO mentions (id, run_id, message_id, from_member_role_id, to_member_name, message) 
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, run_id, message_id, from_member_role_id, to_member_name, message
`

type CreateMentionParams struct {
	ID               string `json:"id"`
	RunID            string `json:"run_id"`
	MessageID        string `json:"message_id"`
	FromMemberRoleID string `json:"from_member_role_id"`
	ToMemberName     string `json:"to_member_name"`
	Message          string `json:"message"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error) {
	row := q.db.QueryRowContext(ctx, createMention,
		arg.ID,
		arg.RunID,
		arg.MessageID,
		arg.FromMemberRoleID,
		arg.ToMemberName,
		arg.Message,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.MessageID,
		&i.FromMemberRoleID,
		&i.ToMemberName,
		&i.Message,
	)
	return i, err
}
