// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_action.sql

package entities

import (
	"context"
	"encoding/json"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions (id, run_id, step_id, tool_call) VALUES (?, ?, ?, ?) RETURNING id, run_id, step_id, tool_call, tool_requirement_message_id, tool_result_message_id
`

type CreateActionParams struct {
	ID       string          `json:"id"`
	RunID    string          `json:"run_id"`
	StepID   string          `json:"step_id"`
	ToolCall json.RawMessage `json:"tool_call"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction,
		arg.ID,
		arg.RunID,
		arg.StepID,
		arg.ToolCall,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}
