// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_run_link.sql

package entities

import (
	"context"
)

const createRunLink = `-- name: CreateRunLink :one
INSERT INTO run_links (parent_run_id, child_run_id, spawning_step_id) VALUES (?, ?, ?) RETURNING parent_run_id, child_run_id, spawning_step_id, linked_at
`

type CreateRunLinkParams struct {
	ParentRunID    string `json:"parent_run_id"`
	ChildRunID     string `json:"child_run_id"`
	SpawningStepID string `json:"spawning_step_id"`
}

func (q *Queries) CreateRunLink(ctx context.Context, arg CreateRunLinkParams) (RunLink, error) {
	row := q.db.QueryRowContext(ctx, createRunLink, arg.ParentRunID, arg.ChildRunID, arg.SpawningStepID)
	var i RunLink
	err := row.Scan(
		&i.ParentRunID,
		&i.ChildRunID,
		&i.SpawningStepID,
		&i.LinkedAt,
	)
	return i, err
}
