// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_task.sql

package entities

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, role_id, prev_id, instruction, model, stream_mode) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, role_id, prev_id, instruction, model, stream_mode
`

type CreateTaskParams struct {
	ID          string         `json:"id"`
	RoleID      string         `json:"role_id"`
	PrevID      sql.NullString `json:"prev_id"`
	Instruction string         `json:"instruction"`
	Model       string         `json:"model"`
	StreamMode  bool           `json:"stream_mode"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.RoleID,
		arg.PrevID,
		arg.Instruction,
		arg.Model,
		arg.StreamMode,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
		&i.Model,
		&i.StreamMode,
	)
	return i, err
}
