// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_step.sql

package entities

import (
	"context"
)

const createStep = `-- name: CreateStep :one
INSERT INTO steps (id, run_id, task_id) VALUES (?, ?, ?) RETURNING id, run_id, task_id, status, created_at
`

type CreateStepParams struct {
	ID     string `json:"id"`
	RunID  string `json:"run_id"`
	TaskID string `json:"task_id"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (Step, error) {
	row := q.db.QueryRowContext(ctx, createStep, arg.ID, arg.RunID, arg.TaskID)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
