// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution.sql

package entities

import (
	"context"
)

const closeExecution = `-- name: CloseExecution :one
UPDATE executions SET status = 'closed' WHERE id = ? RETURNING id, kind, status, created_at
`

func (q *Queries) CloseExecution(ctx context.Context, id string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, closeExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (id, kind) VALUES (?, ?) RETURNING id, kind, status, created_at
`

type CreateExecutionParams struct {
	ID   string `json:"id"`
	Kind string `json:"kind"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, createExecution, arg.ID, arg.Kind)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createExecutionLink = `-- name: CreateExecutionLink :one
INSERT INTO execution_links (parent_id, child_id) VALUES (?, ?) RETURNING parent_id, child_id, linked_at
`

type CreateExecutionLinkParams struct {
	ParentID string `json:"parent_id"`
	ChildID  string `json:"child_id"`
}

func (q *Queries) CreateExecutionLink(ctx context.Context, arg CreateExecutionLinkParams) (ExecutionLink, error) {
	row := q.db.QueryRowContext(ctx, createExecutionLink, arg.ParentID, arg.ChildID)
	var i ExecutionLink
	err := row.Scan(&i.ParentID, &i.ChildID, &i.LinkedAt)
	return i, err
}

const getAllExecutions = `-- name: GetAllExecutions :many
SELECT id, kind, status, created_at FROM executions e
ORDER BY e.id ASC
`

func (q *Queries) GetAllExecutions(ctx context.Context) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getAllExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildExecutions = `-- name: GetChildExecutions :many
SELECT 
    child.id, child.kind, child.status, child.created_at
FROM executions AS child
INNER JOIN execution_links AS el ON child.id = el.child_id
WHERE 
    el.parent_id = ?
ORDER BY child.id DESC
`

func (q *Queries) GetChildExecutions(ctx context.Context, parentID string) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getChildExecutions, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecution = `-- name: GetExecution :one
SELECT id, kind, status, created_at FROM executions WHERE id = ? LIMIT 1
`

func (q *Queries) GetExecution(ctx context.Context, id string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenExecutions = `-- name: GetOpenExecutions :many
SELECT id, kind, status, created_at 
FROM executions 
WHERE status = 'open' 
ORDER BY id DESC
`

func (q *Queries) GetOpenExecutions(ctx context.Context) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getOpenExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
