// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_channel.sql

package entities

import (
	"context"
)

const getChannel = `-- name: GetChannel :one
SELECT name, description FROM channels WHERE name = ? LIMIT 1
`

func (q *Queries) GetChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, name)
	var i Channel
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}
