// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_action_by_run.sql

package entities

import (
	"context"
)

const getActionByRun = `-- name: GetActionByRun :one
SELECT id, run_id, tool_call, tool_requirement_message_id, tool_result_message_id FROM actions WHERE run_id = ? LIMIT 1
`

func (q *Queries) GetActionByRun(ctx context.Context, runID string) (Action, error) {
	row := q.db.QueryRowContext(ctx, getActionByRun, runID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}
