// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_tools_by_task.sql

package entities

import (
	"context"
)

const getToolsByTask = `-- name: GetToolsByTask :many
SELECT id, task_id, name, description, parameters FROM tools WHERE task_id = ?
`

func (q *Queries) GetToolsByTask(ctx context.Context, taskID string) ([]Tool, error) {
	rows, err := q.db.QueryContext(ctx, getToolsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.Description,
			&i.Parameters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
