// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_llm_chunk_response_by_step.sql

package entities

import (
	"context"
)

const getLlmChunkResponseByStep = `-- name: GetLlmChunkResponseByStep :many
SELECT id, sequence_number, step_id, task_id, openai_chunk_response, created_at FROM llm_chunk_responses WHERE step_id = ? ORDER BY sequence_number ASC
`

func (q *Queries) GetLlmChunkResponseByStep(ctx context.Context, stepID string) ([]LlmChunkResponse, error) {
	rows, err := q.db.QueryContext(ctx, getLlmChunkResponseByStep, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmChunkResponse
	for rows.Next() {
		var i LlmChunkResponse
		if err := rows.Scan(
			&i.ID,
			&i.SequenceNumber,
			&i.StepID,
			&i.TaskID,
			&i.OpenaiChunkResponse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
