// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_role_by_member_and_channel.sql

package entities

import (
	"context"
)

const getRoleByMemberAndChannel = `-- name: GetRoleByMemberAndChannel :one
SELECT id, member_name, channel_name FROM roles WHERE member_name = ? AND channel_name = ? LIMIT 1
`

type GetRoleByMemberAndChannelParams struct {
	MemberName  string `json:"member_name"`
	ChannelName string `json:"channel_name"`
}

func (q *Queries) GetRoleByMemberAndChannel(ctx context.Context, arg GetRoleByMemberAndChannelParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByMemberAndChannel, arg.MemberName, arg.ChannelName)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}
