// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_task.sql

package entities

import (
	"context"
)

const getTask = `-- name: GetTask :one
SELECT id, role_id, prev_id, instruction, model, stream_mode FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
		&i.Model,
		&i.StreamMode,
	)
	return i, err
}
