// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_role_by_channel.sql

package entities

import (
	"context"
)

const getRoleByChannel = `-- name: GetRoleByChannel :many
SELECT id, member_name, channel_name FROM roles WHERE channel_name = ?
`

func (q *Queries) GetRoleByChannel(ctx context.Context, channelName string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoleByChannel, channelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.MemberName, &i.ChannelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
