// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_action_by_step.sql

package entities

import (
	"context"
)

const getActionByStep = `-- name: GetActionByStep :many
SELECT id, run_id, step_id, tool_call, tool_requirement_message_id, tool_result_message_id FROM actions WHERE step_id = ?
`

func (q *Queries) GetActionByStep(ctx context.Context, stepID string) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, getActionByStep, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepID,
			&i.ToolCall,
			&i.ToolRequirementMessageID,
			&i.ToolResultMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
