// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_pending_steps_by_run.sql

package entities

import (
	"context"
)

const getPendingStepsByRun = `-- name: GetPendingStepsByRun :many
SELECT id, run_id, task_id, status, created_at FROM steps WHERE run_id = ? AND status = 'pending'
`

func (q *Queries) GetPendingStepsByRun(ctx context.Context, runID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, getPendingStepsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TaskID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
