// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_mentions_by_source_step.sql

package entities

import (
	"context"
)

const getMentionsBySourceStep = `-- name: GetMentionsBySourceStep :many
SELECT m.id, m.run_id, m.from_member_task_id, m.to_member_name, m.message FROM mentions m
INNER JOIN runs r ON m.run_id = r.id
WHERE r.source_step_id = ?
ORDER BY m.id ASC
`

func (q *Queries) GetMentionsBySourceStep(ctx context.Context, sourceStepID string) ([]Mention, error) {
	rows, err := q.db.QueryContext(ctx, getMentionsBySourceStep, sourceStepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mention
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FromMemberTaskID,
			&i.ToMemberName,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
