// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_runs_by_spawning_step.sql

package entities

import (
	"context"
	"time"
)

const getRunsBySpawningStepId = `-- name: GetRunsBySpawningStepId :many
SELECT id, kind, status, created_at, parent_run_id, child_run_id, spawning_step_id, linked_at FROM runs r
INNER JOIN run_links rl ON r.id = rl.child_run_id
WHERE rl.spawning_step_id = ?
`

type GetRunsBySpawningStepIdRow struct {
	ID             string    `json:"id"`
	Kind           string    `json:"kind"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	ParentRunID    string    `json:"parent_run_id"`
	ChildRunID     string    `json:"child_run_id"`
	SpawningStepID string    `json:"spawning_step_id"`
	LinkedAt       time.Time `json:"linked_at"`
}

func (q *Queries) GetRunsBySpawningStepId(ctx context.Context, spawningStepID string) ([]GetRunsBySpawningStepIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRunsBySpawningStepId, spawningStepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRunsBySpawningStepIdRow
	for rows.Next() {
		var i GetRunsBySpawningStepIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
			&i.ParentRunID,
			&i.ChildRunID,
			&i.SpawningStepID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
