// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_runs_by_source_step.sql

package entities

import (
	"context"
)

const getRunsBySourceStep = `-- name: GetRunsBySourceStep :many
SELECT id, source_step_id, created_at FROM runs WHERE source_step_id = ?
`

func (q *Queries) GetRunsBySourceStep(ctx context.Context, sourceStepID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, getRunsBySourceStep, sourceStepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(&i.ID, &i.SourceStepID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
