// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_message.sql

package entities

import (
	"context"
)

const getMessage = `-- name: GetMessage :one
SELECT id, step_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.ChannelName,
		&i.RoleID,
		&i.TaskID,
		&i.Visibility,
		&i.OpenaiMessage,
		&i.CreatedAt,
	)
	return i, err
}
