// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_step.sql

package entities

import (
	"context"
)

const getStep = `-- name: GetStep :one
SELECT id, run_id, task_id, status, created_at FROM steps WHERE id = ? LIMIT 1
`

func (q *Queries) GetStep(ctx context.Context, id string) (Step, error) {
	row := q.db.QueryRowContext(ctx, getStep, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
