// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_mention.sql

package entities

import (
	"context"
)

const getMention = `-- name: GetMention :one
SELECT a.id, a.run_id, a.from_member_task_id, a.to_member_name, a.message FROM mentions a
WHERE a.id = ?
LIMIT 1
`

func (q *Queries) GetMention(ctx context.Context, id string) (Mention, error) {
	row := q.db.QueryRowContext(ctx, getMention, id)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FromMemberTaskID,
		&i.ToMemberName,
		&i.Message,
	)
	return i, err
}
