// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_member.sql

package entities

import (
	"context"
)

const getMember = `-- name: GetMember :one
SELECT name, kind FROM members WHERE name = ? LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, name string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, name)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}
