// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_role.sql

package entities

import (
	"context"
)

const getRole = `-- name: GetRole :one
SELECT id, member_name, channel_name FROM roles WHERE id = ? LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}
