// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_mentions_by_run.sql

package entities

import (
	"context"
)

const getMentionsByRun = `-- name: GetMentionsByRun :many
SELECT a.id, a.run_id, a.from_member_task_id, a.to_member_name, a.message FROM mentions a
WHERE a.run_id = ?
ORDER BY a.id ASC
`

func (q *Queries) GetMentionsByRun(ctx context.Context, runID string) ([]Mention, error) {
	rows, err := q.db.QueryContext(ctx, getMentionsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mention
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FromMemberTaskID,
			&i.ToMemberName,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
