// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_run.sql

package entities

import (
	"context"
)

const getRun = `-- name: GetRun :one
SELECT id, mention_id, status, created_at FROM runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
