// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_member_by_task.sql

package entities

import (
	"context"
)

const getMemberByTask = `-- name: GetMemberByTask :one
SELECT m.name, m.kind FROM members m
JOIN roles r ON r.member_name = m.name
JOIN tasks d ON d.role_id = r.id
WHERE d.id = ?
LIMIT 1
`

func (q *Queries) GetMemberByTask(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByTask, id)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}
