// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_parent_run_link.sql

package entities

import (
	"context"
)

const getParentRunLink = `-- name: GetParentRunLink :one
SELECT parent_run_id, child_run_id, spawning_step_id, linked_at FROM run_links WHERE child_run_id = ? LIMIT 1
`

func (q *Queries) GetParentRunLink(ctx context.Context, childRunID string) (RunLink, error) {
	row := q.db.QueryRowContext(ctx, getParentRunLink, childRunID)
	var i RunLink
	err := row.Scan(
		&i.ParentRunID,
		&i.ChildRunID,
		&i.SpawningStepID,
		&i.LinkedAt,
	)
	return i, err
}
