// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_mention_by_run.sql

package entities

import (
	"context"
)

const getMentionByRun = `-- name: GetMentionByRun :one
SELECT a.id, a.run_id, a.message_id, a.from_member_role_id, a.to_member_name, a.message FROM mentions a
WHERE a.run_id = ?
LIMIT 1
`

func (q *Queries) GetMentionByRun(ctx context.Context, runID string) (Mention, error) {
	row := q.db.QueryRowContext(ctx, getMentionByRun, runID)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.MessageID,
		&i.FromMemberRoleID,
		&i.ToMemberName,
		&i.Message,
	)
	return i, err
}
