// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_llm_response_by_step.sql

package entities

import (
	"context"
)

const getLlmResponseByStep = `-- name: GetLlmResponseByStep :one
SELECT id, step_id, task_id, openai_response, created_at FROM llm_responses WHERE step_id = ? LIMIT 1
`

func (q *Queries) GetLlmResponseByStep(ctx context.Context, stepID string) (LlmResponse, error) {
	row := q.db.QueryRowContext(ctx, getLlmResponseByStep, stepID)
	var i LlmResponse
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.TaskID,
		&i.OpenaiResponse,
		&i.CreatedAt,
	)
	return i, err
}
