// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_steps.sql

package entities

import (
	"context"
)

const getSteps = `-- name: GetSteps :many
SELECT id, run_id, kind, created_at FROM steps ORDER BY id ASC
`

func (q *Queries) GetSteps(ctx context.Context) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, getSteps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
