// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_member_by_role.sql

package entities

import (
	"context"
)

const getMemberByRole = `-- name: GetMemberByRole :one
SELECT m.name, m.kind FROM members m
JOIN roles r ON r.member_name = m.name
WHERE r.id = ?
LIMIT 1
`

func (q *Queries) GetMemberByRole(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByRole, id)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}
