// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_message_by_step.sql

package entities

import (
	"context"
)

const getMessageByStep = `-- name: GetMessageByStep :one
SELECT id, step_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages WHERE step_id = ? LIMIT 1
`

func (q *Queries) GetMessageByStep(ctx context.Context, stepID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByStep, stepID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.ChannelName,
		&i.RoleID,
		&i.TaskID,
		&i.Visibility,
		&i.OpenaiMessage,
		&i.CreatedAt,
	)
	return i, err
}
