// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_channel_by_role.sql

package entities

import (
	"context"
)

const getChannelByRole = `-- name: GetChannelByRole :one
SELECT c.name, c.description FROM channels c
JOIN roles r ON r.channel_name = c.name
WHERE r.id = ?
LIMIT 1
`

func (q *Queries) GetChannelByRole(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByRole, id)
	var i Channel
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}
