// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_incomplete_runs_and_children.sql

package entities

import (
	"context"
	"database/sql"
)

const getIncompleteRunsAndChildren = `-- name: GetIncompleteRunsAndChildren :many
SELECT 
    r.id AS run_id,
    r.status AS run_status,
    rl.child_run_id AS child_run_id,
    child.status AS child_status
FROM runs r
LEFT JOIN run_links rl ON r.id = rl.parent_run_id
LEFT JOIN runs child ON rl.child_run_id = child.id
WHERE r.status != 'completed'
`

type GetIncompleteRunsAndChildrenRow struct {
	RunID       string         `json:"run_id"`
	RunStatus   string         `json:"run_status"`
	ChildRunID  sql.NullString `json:"child_run_id"`
	ChildStatus sql.NullString `json:"child_status"`
}

func (q *Queries) GetIncompleteRunsAndChildren(ctx context.Context) ([]GetIncompleteRunsAndChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncompleteRunsAndChildren)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncompleteRunsAndChildrenRow
	for rows.Next() {
		var i GetIncompleteRunsAndChildrenRow
		if err := rows.Scan(
			&i.RunID,
			&i.RunStatus,
			&i.ChildRunID,
			&i.ChildStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
