// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_runs.sql

package entities

import (
	"context"
)

const getAllRuns = `-- name: GetAllRuns :many
SELECT id, kind, status, created_at FROM runs r
ORDER BY id ASC
`

func (q *Queries) GetAllRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, getAllRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
