// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_context_messages.sql

package entities

import (
	"context"
)

const getContextMessages = `-- name: GetContextMessages :many
SELECT id, step_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages 
WHERE 
    (visibility = 'task' AND task_id = ?) OR
    (visibility = 'role' AND role_id = ?) OR
    (visibility = 'channel' AND channel_name = ?)
ORDER BY created_at ASC
`

type GetContextMessagesParams struct {
	TaskID      string `json:"task_id"`
	RoleID      string `json:"role_id"`
	ChannelName string `json:"channel_name"`
}

func (q *Queries) GetContextMessages(ctx context.Context, arg GetContextMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getContextMessages, arg.TaskID, arg.RoleID, arg.ChannelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.ChannelName,
			&i.RoleID,
			&i.TaskID,
			&i.Visibility,
			&i.OpenaiMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
