// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_action.sql

package entities

import (
	"context"
)

const getAction = `-- name: GetAction :one
SELECT id, run_id, step_id, tool_call, tool_requirement_message_id, tool_result_message_id FROM actions WHERE id = ? LIMIT 1
`

func (q *Queries) GetAction(ctx context.Context, id string) (Action, error) {
	row := q.db.QueryRowContext(ctx, getAction, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}
