// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_role_by_task.sql

package entities

import (
	"context"
)

const getRoleByTask = `-- name: GetRoleByTask :one
SELECT r.id, r.member_name, r.channel_name FROM roles r
JOIN tasks d ON d.role_id = r.id
WHERE d.id = ?
LIMIT 1
`

func (q *Queries) GetRoleByTask(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByTask, id)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}
