// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_mentions_by_message.sql

package entities

import (
	"context"
)

const getMentionsByMessageId = `-- name: GetMentionsByMessageId :one
SELECT m.id, m.message_id, m.from_member_role_id, m.to_member_name, m.message FROM mentions m WHERE m.message_id = ?
`

func (q *Queries) GetMentionsByMessageId(ctx context.Context, messageID string) (Mention, error) {
	row := q.db.QueryRowContext(ctx, getMentionsByMessageId, messageID)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FromMemberRoleID,
		&i.ToMemberName,
		&i.Message,
	)
	return i, err
}
