// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_task_by_step.sql

package entities

import (
	"context"
)

const getTaskByStep = `-- name: GetTaskByStep :one
SELECT d.id, d.role_id, d.prev_id, d.instruction, d.model, d.stream_mode
FROM tasks d
WHERE d.id = COALESCE(
  (SELECT m.task_id FROM messages m WHERE m.step_id = ?1 LIMIT 1),
  (SELECT r.task_id FROM llm_responses r WHERE r.step_id = ?1 LIMIT 1),
  (SELECT c.task_id FROM llm_chunk_responses c WHERE c.step_id = ?1 LIMIT 1)
)
LIMIT 1
`

func (q *Queries) GetTaskByStep(ctx context.Context, stepID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByStep, stepID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
		&i.Model,
		&i.StreamMode,
	)
	return i, err
}
