// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_first_task.sql

package entities

import (
	"context"
)

const getFirstTask = `-- name: GetFirstTask :one
SELECT id, role_id, prev_id, instruction, model, stream_mode FROM tasks
WHERE role_id = ?
AND prev_id IS NULL
LIMIT 1
`

func (q *Queries) GetFirstTask(ctx context.Context, roleID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getFirstTask, roleID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
		&i.Model,
		&i.StreamMode,
	)
	return i, err
}
