// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_chunk_response.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmChunkResponses = `-- name: CreateLlmChunkResponses :exec
INSERT INTO llm_chunk_responses (execution_id, sequence_number, openai_chunk_response) VALUES (?, ?, ?)
`

type CreateLlmChunkResponsesParams struct {
	ExecutionID         string          `json:"execution_id"`
	SequenceNumber      int64           `json:"sequence_number"`
	OpenaiChunkResponse json.RawMessage `json:"openai_chunk_response"`
}

func (q *Queries) CreateLlmChunkResponses(ctx context.Context, arg CreateLlmChunkResponsesParams) error {
	_, err := q.db.ExecContext(ctx, createLlmChunkResponses, arg.ExecutionID, arg.SequenceNumber, arg.OpenaiChunkResponse)
	return err
}

const getLlmChunkResponse = `-- name: GetLlmChunkResponse :many
SELECT execution_id, sequence_number, openai_chunk_response FROM llm_chunk_responses WHERE execution_id = ? ORDER BY sequence_number ASC
`

func (q *Queries) GetLlmChunkResponse(ctx context.Context, executionID string) ([]LlmChunkResponse, error) {
	rows, err := q.db.QueryContext(ctx, getLlmChunkResponse, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmChunkResponse
	for rows.Next() {
		var i LlmChunkResponse
		if err := rows.Scan(&i.ExecutionID, &i.SequenceNumber, &i.OpenaiChunkResponse); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
