// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_chunk_response.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmChunkResponses = `-- name: CreateLlmChunkResponses :exec
INSERT INTO llm_chunk_responses (id, sequence_number, openai_chunk_response) VALUES (?, ?, ?)
`

type CreateLlmChunkResponsesParams struct {
	ID                  string          `json:"id"`
	SequenceNumber      int64           `json:"sequence_number"`
	OpenaiChunkResponse json.RawMessage `json:"openai_chunk_response"`
}

func (q *Queries) CreateLlmChunkResponses(ctx context.Context, arg CreateLlmChunkResponsesParams) error {
	_, err := q.db.ExecContext(ctx, createLlmChunkResponses, arg.ID, arg.SequenceNumber, arg.OpenaiChunkResponse)
	return err
}

const getLlmChunkResponseByExecution = `-- name: GetLlmChunkResponseByExecution :many
SELECT 
    response.execution_id AS execution_id, 
    chunk.id AS id,
    chunk.sequence_number AS sequence_number,
    chunk.openai_chunk_response AS openai_chunk_response
FROM llm_chunk_responses AS chunk
INNER JOIN llm_responses AS response ON chunk.id = response.id
WHERE response.execution_id = ? 
ORDER BY chunk.sequence_number ASC
`

type GetLlmChunkResponseByExecutionRow struct {
	ExecutionID         string          `json:"execution_id"`
	ID                  string          `json:"id"`
	SequenceNumber      int64           `json:"sequence_number"`
	OpenaiChunkResponse json.RawMessage `json:"openai_chunk_response"`
}

func (q *Queries) GetLlmChunkResponseByExecution(ctx context.Context, executionID string) ([]GetLlmChunkResponseByExecutionRow, error) {
	rows, err := q.db.QueryContext(ctx, getLlmChunkResponseByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLlmChunkResponseByExecutionRow
	for rows.Next() {
		var i GetLlmChunkResponseByExecutionRow
		if err := rows.Scan(
			&i.ExecutionID,
			&i.ID,
			&i.SequenceNumber,
			&i.OpenaiChunkResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
