// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_request.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmRequest = `-- name: CreateLlmRequest :one
INSERT INTO llm_requests (id, execution_id, task_id, openai_request) VALUES (?, ?, ?, ?) RETURNING id, execution_id, task_id, openai_request, created_at
`

type CreateLlmRequestParams struct {
	ID            string          `json:"id"`
	ExecutionID   string          `json:"execution_id"`
	TaskID        string          `json:"task_id"`
	OpenaiRequest json.RawMessage `json:"openai_request"`
}

func (q *Queries) CreateLlmRequest(ctx context.Context, arg CreateLlmRequestParams) (LlmRequest, error) {
	row := q.db.QueryRowContext(ctx, createLlmRequest,
		arg.ID,
		arg.ExecutionID,
		arg.TaskID,
		arg.OpenaiRequest,
	)
	var i LlmRequest
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.TaskID,
		&i.OpenaiRequest,
		&i.CreatedAt,
	)
	return i, err
}

const getLlmRequestByExecution = `-- name: GetLlmRequestByExecution :one
SELECT id, execution_id, task_id, openai_request, created_at FROM llm_requests WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetLlmRequestByExecution(ctx context.Context, executionID string) (LlmRequest, error) {
	row := q.db.QueryRowContext(ctx, getLlmRequestByExecution, executionID)
	var i LlmRequest
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.TaskID,
		&i.OpenaiRequest,
		&i.CreatedAt,
	)
	return i, err
}

const getPartialLlmRequest = `-- name: GetPartialLlmRequest :one
SELECT id, execution_id, task_id FROM llm_requests WHERE id = ? LIMIT 1
`

type GetPartialLlmRequestRow struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
	TaskID      string `json:"task_id"`
}

func (q *Queries) GetPartialLlmRequest(ctx context.Context, id string) (GetPartialLlmRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getPartialLlmRequest, id)
	var i GetPartialLlmRequestRow
	err := row.Scan(&i.ID, &i.ExecutionID, &i.TaskID)
	return i, err
}

const getPartialLlmRequestByExecution = `-- name: GetPartialLlmRequestByExecution :one
SELECT id, execution_id, task_id FROM llm_requests WHERE execution_id = ? LIMIT 1
`

type GetPartialLlmRequestByExecutionRow struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
	TaskID      string `json:"task_id"`
}

func (q *Queries) GetPartialLlmRequestByExecution(ctx context.Context, executionID string) (GetPartialLlmRequestByExecutionRow, error) {
	row := q.db.QueryRowContext(ctx, getPartialLlmRequestByExecution, executionID)
	var i GetPartialLlmRequestByExecutionRow
	err := row.Scan(&i.ID, &i.ExecutionID, &i.TaskID)
	return i, err
}
