// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_bulk_response.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmBulkResponse = `-- name: CreateLlmBulkResponse :one
INSERT INTO llm_bulk_responses (execution_id, openai_response) VALUES (?, ?) RETURNING execution_id, openai_response
`

type CreateLlmBulkResponseParams struct {
	ExecutionID    string          `json:"execution_id"`
	OpenaiResponse json.RawMessage `json:"openai_response"`
}

func (q *Queries) CreateLlmBulkResponse(ctx context.Context, arg CreateLlmBulkResponseParams) (LlmBulkResponse, error) {
	row := q.db.QueryRowContext(ctx, createLlmBulkResponse, arg.ExecutionID, arg.OpenaiResponse)
	var i LlmBulkResponse
	err := row.Scan(&i.ExecutionID, &i.OpenaiResponse)
	return i, err
}

const getLlmBulkResponse = `-- name: GetLlmBulkResponse :one
SELECT execution_id, openai_response FROM llm_bulk_responses WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetLlmBulkResponse(ctx context.Context, executionID string) (LlmBulkResponse, error) {
	row := q.db.QueryRowContext(ctx, getLlmBulkResponse, executionID)
	var i LlmBulkResponse
	err := row.Scan(&i.ExecutionID, &i.OpenaiResponse)
	return i, err
}
