// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_response.sql

package entities

import (
	"context"
)

const createLlmResponse = `-- name: CreateLlmResponse :one
INSERT INTO llm_responses (execution_id, kind) VALUES (?, ?) RETURNING execution_id, created_at, kind
`

type CreateLlmResponseParams struct {
	ExecutionID string `json:"execution_id"`
	Kind        string `json:"kind"`
}

func (q *Queries) CreateLlmResponse(ctx context.Context, arg CreateLlmResponseParams) (LlmResponse, error) {
	row := q.db.QueryRowContext(ctx, createLlmResponse, arg.ExecutionID, arg.Kind)
	var i LlmResponse
	err := row.Scan(&i.ExecutionID, &i.CreatedAt, &i.Kind)
	return i, err
}

const getLlmResponse = `-- name: GetLlmResponse :one
SELECT execution_id, created_at, kind FROM llm_responses WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetLlmResponse(ctx context.Context, executionID string) (LlmResponse, error) {
	row := q.db.QueryRowContext(ctx, getLlmResponse, executionID)
	var i LlmResponse
	err := row.Scan(&i.ExecutionID, &i.CreatedAt, &i.Kind)
	return i, err
}
