// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_request.sql

package entities

import (
	"context"
	"encoding/json"
)

const createLlmRequest = `-- name: CreateLlmRequest :one
INSERT INTO llm_requests (execution_id, task_id, openai_request) VALUES (?, ?, ?) RETURNING execution_id, task_id, openai_request, created_at
`

type CreateLlmRequestParams struct {
	ExecutionID   string          `json:"execution_id"`
	TaskID        string          `json:"task_id"`
	OpenaiRequest json.RawMessage `json:"openai_request"`
}

func (q *Queries) CreateLlmRequest(ctx context.Context, arg CreateLlmRequestParams) (LlmRequest, error) {
	row := q.db.QueryRowContext(ctx, createLlmRequest, arg.ExecutionID, arg.TaskID, arg.OpenaiRequest)
	var i LlmRequest
	err := row.Scan(
		&i.ExecutionID,
		&i.TaskID,
		&i.OpenaiRequest,
		&i.CreatedAt,
	)
	return i, err
}

const getLlmRequest = `-- name: GetLlmRequest :one
SELECT execution_id, task_id, openai_request, created_at FROM llm_requests WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetLlmRequest(ctx context.Context, executionID string) (LlmRequest, error) {
	row := q.db.QueryRowContext(ctx, getLlmRequest, executionID)
	var i LlmRequest
	err := row.Scan(
		&i.ExecutionID,
		&i.TaskID,
		&i.OpenaiRequest,
		&i.CreatedAt,
	)
	return i, err
}
