// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package entities

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (name, kind) VALUES (?, ?) RETURNING name, kind
`

type CreateMemberParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember, arg.Name, arg.Kind)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT name, kind FROM members WHERE name = ? LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, name string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, name)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}

const getMemberByRole = `-- name: GetMemberByRole :one
SELECT m.name, m.kind FROM members m
JOIN roles r ON r.member_name = m.name
WHERE r.id = ?
LIMIT 1
`

func (q *Queries) GetMemberByRole(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByRole, id)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}

const getMemberByTask = `-- name: GetMemberByTask :one
SELECT m.name, m.kind FROM members m
JOIN roles r ON r.member_name = m.name
JOIN tasks d ON d.role_id = r.id
WHERE d.id = ?
LIMIT 1
`

func (q *Queries) GetMemberByTask(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByTask, id)
	var i Member
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}

const getMembers = `-- name: GetMembers :many
SELECT name, kind FROM members
`

func (q *Queries) GetMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, getMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
