// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mention.sql

package entities

import (
	"context"
)

const createMention = `-- name: CreateMention :one
INSERT INTO mentions (execution_id, message_id, from_member_role_id, to_member_name, message) 
VALUES (?, ?, ?, ?, ?) RETURNING execution_id, message_id, from_member_role_id, to_member_name, message
`

type CreateMentionParams struct {
	ExecutionID      string `json:"execution_id"`
	MessageID        string `json:"message_id"`
	FromMemberRoleID string `json:"from_member_role_id"`
	ToMemberName     string `json:"to_member_name"`
	Message          string `json:"message"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error) {
	row := q.db.QueryRowContext(ctx, createMention,
		arg.ExecutionID,
		arg.MessageID,
		arg.FromMemberRoleID,
		arg.ToMemberName,
		arg.Message,
	)
	var i Mention
	err := row.Scan(
		&i.ExecutionID,
		&i.MessageID,
		&i.FromMemberRoleID,
		&i.ToMemberName,
		&i.Message,
	)
	return i, err
}

const getMention = `-- name: GetMention :one
SELECT execution_id, message_id, from_member_role_id, to_member_name, message FROM mentions WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetMention(ctx context.Context, executionID string) (Mention, error) {
	row := q.db.QueryRowContext(ctx, getMention, executionID)
	var i Mention
	err := row.Scan(
		&i.ExecutionID,
		&i.MessageID,
		&i.FromMemberRoleID,
		&i.ToMemberName,
		&i.Message,
	)
	return i, err
}
