// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package entities

import (
	"context"
	"encoding/json"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, execution_id, channel_name, role_id, task_id, visibility, openai_message) 
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, execution_id, channel_name, role_id, task_id, visibility, openai_message, created_at
`

type CreateMessageParams struct {
	ID            string          `json:"id"`
	ExecutionID   string          `json:"execution_id"`
	ChannelName   string          `json:"channel_name"`
	RoleID        string          `json:"role_id"`
	TaskID        interface{}     `json:"task_id"`
	Visibility    string          `json:"visibility"`
	OpenaiMessage json.RawMessage `json:"openai_message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ExecutionID,
		arg.ChannelName,
		arg.RoleID,
		arg.TaskID,
		arg.Visibility,
		arg.OpenaiMessage,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.ChannelName,
		&i.RoleID,
		&i.TaskID,
		&i.Visibility,
		&i.OpenaiMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getContextMessages = `-- name: GetContextMessages :many
SELECT id, execution_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages 
WHERE 
    (visibility = 'task' AND task_id = ?) OR
    (visibility = 'role' AND role_id = ?) OR
    (visibility = 'channel' AND channel_name = ?)
ORDER BY id ASC
`

type GetContextMessagesParams struct {
	TaskID      interface{} `json:"task_id"`
	RoleID      string      `json:"role_id"`
	ChannelName string      `json:"channel_name"`
}

func (q *Queries) GetContextMessages(ctx context.Context, arg GetContextMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getContextMessages, arg.TaskID, arg.RoleID, arg.ChannelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.ChannelName,
			&i.RoleID,
			&i.TaskID,
			&i.Visibility,
			&i.OpenaiMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, execution_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.ChannelName,
		&i.RoleID,
		&i.TaskID,
		&i.Visibility,
		&i.OpenaiMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, execution_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages ORDER BY id ASC
`

func (q *Queries) GetMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.ChannelName,
			&i.RoleID,
			&i.TaskID,
			&i.Visibility,
			&i.OpenaiMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByExecution = `-- name: GetMessagesByExecution :many
SELECT id, execution_id, channel_name, role_id, task_id, visibility, openai_message, created_at FROM messages WHERE execution_id = ? ORDER BY id ASC
`

func (q *Queries) GetMessagesByExecution(ctx context.Context, executionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.ChannelName,
			&i.RoleID,
			&i.TaskID,
			&i.Visibility,
			&i.OpenaiMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
