// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entities

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Action struct {
	ID                       string          `json:"id"`
	ExecutionID              string          `json:"execution_id"`
	LlmResponseID            string          `json:"llm_response_id"`
	ToolCall                 json.RawMessage `json:"tool_call"`
	ToolRequirementMessageID interface{}     `json:"tool_requirement_message_id"`
	ToolResultMessageID      interface{}     `json:"tool_result_message_id"`
}

type Channel struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Execution struct {
	ID        string    `json:"id"`
	Kind      string    `json:"kind"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type ExecutionLink struct {
	ParentID string    `json:"parent_id"`
	ChildID  string    `json:"child_id"`
	LinkedAt time.Time `json:"linked_at"`
}

type LlmBulkResponse struct {
	ID             string          `json:"id"`
	OpenaiResponse json.RawMessage `json:"openai_response"`
}

type LlmChunkResponse struct {
	ID                  string          `json:"id"`
	SequenceNumber      int64           `json:"sequence_number"`
	OpenaiChunkResponse json.RawMessage `json:"openai_chunk_response"`
}

type LlmRequest struct {
	ID            string          `json:"id"`
	ExecutionID   string          `json:"execution_id"`
	TaskID        string          `json:"task_id"`
	OpenaiRequest json.RawMessage `json:"openai_request"`
	CreatedAt     time.Time       `json:"created_at"`
}

type LlmResponse struct {
	ID          string    `json:"id"`
	ExecutionID string    `json:"execution_id"`
	CreatedAt   time.Time `json:"created_at"`
	Kind        string    `json:"kind"`
}

type Member struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

type Mention struct {
	ID               string `json:"id"`
	ExecutionID      string `json:"execution_id"`
	MessageID        string `json:"message_id"`
	FromMemberRoleID string `json:"from_member_role_id"`
	ToMemberName     string `json:"to_member_name"`
	Message          string `json:"message"`
}

type Message struct {
	ID            string          `json:"id"`
	ExecutionID   string          `json:"execution_id"`
	ChannelName   string          `json:"channel_name"`
	RoleID        string          `json:"role_id"`
	TaskID        interface{}     `json:"task_id"`
	Visibility    string          `json:"visibility"`
	OpenaiMessage json.RawMessage `json:"openai_message"`
	CreatedAt     time.Time       `json:"created_at"`
}

type ReactLoop struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
	TaskID      string `json:"task_id"`
	Status      string `json:"status"`
}

type Role struct {
	ID          string `json:"id"`
	MemberName  string `json:"member_name"`
	ChannelName string `json:"channel_name"`
}

type Task struct {
	ID          string         `json:"id"`
	RoleID      string         `json:"role_id"`
	PrevID      sql.NullString `json:"prev_id"`
	Instruction string         `json:"instruction"`
}

type TaskExecution struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
}

type TaskLink struct {
	ParentID  string    `json:"parent_id"`
	ChildID   string    `json:"child_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Tool struct {
	ID     string          `json:"id"`
	TaskID string          `json:"task_id"`
	Tool   json.RawMessage `json:"tool"`
}
