// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: react_loop.sql

package entities

import (
	"context"
)

const createReactLoop = `-- name: CreateReactLoop :one
INSERT INTO react_loops (id, execution_id, task_id) VALUES (?, ?, ?) RETURNING id, execution_id, task_id, status
`

type CreateReactLoopParams struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
	TaskID      string `json:"task_id"`
}

func (q *Queries) CreateReactLoop(ctx context.Context, arg CreateReactLoopParams) (ReactLoop, error) {
	row := q.db.QueryRowContext(ctx, createReactLoop, arg.ID, arg.ExecutionID, arg.TaskID)
	var i ReactLoop
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.TaskID,
		&i.Status,
	)
	return i, err
}

const getReactLoop = `-- name: GetReactLoop :one
SELECT id, execution_id, task_id, status FROM react_loops WHERE id = ? LIMIT 1
`

func (q *Queries) GetReactLoop(ctx context.Context, id string) (ReactLoop, error) {
	row := q.db.QueryRowContext(ctx, getReactLoop, id)
	var i ReactLoop
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.TaskID,
		&i.Status,
	)
	return i, err
}

const getReactLoopByExecution = `-- name: GetReactLoopByExecution :one
SELECT id, execution_id, task_id, status FROM react_loops WHERE execution_id = ? ORDER BY id ASC
`

func (q *Queries) GetReactLoopByExecution(ctx context.Context, executionID string) (ReactLoop, error) {
	row := q.db.QueryRowContext(ctx, getReactLoopByExecution, executionID)
	var i ReactLoop
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.TaskID,
		&i.Status,
	)
	return i, err
}

const getReactLoops = `-- name: GetReactLoops :many
SELECT id, execution_id, task_id, status FROM react_loops ORDER BY id ASC
`

func (q *Queries) GetReactLoops(ctx context.Context) ([]ReactLoop, error) {
	rows, err := q.db.QueryContext(ctx, getReactLoops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReactLoop
	for rows.Next() {
		var i ReactLoop
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.TaskID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReactLoopStatus = `-- name: UpdateReactLoopStatus :one
UPDATE react_loops SET status = ? WHERE id = ? RETURNING id, execution_id, task_id, status
`

type UpdateReactLoopStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateReactLoopStatus(ctx context.Context, arg UpdateReactLoopStatusParams) (ReactLoop, error) {
	row := q.db.QueryRowContext(ctx, updateReactLoopStatus, arg.Status, arg.ID)
	var i ReactLoop
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.TaskID,
		&i.Status,
	)
	return i, err
}
