// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package entities

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, member_name, channel_name) VALUES (?, ?, ?) RETURNING id, member_name, channel_name
`

type CreateRoleParams struct {
	ID          string `json:"id"`
	MemberName  string `json:"member_name"`
	ChannelName string `json:"channel_name"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.ID, arg.MemberName, arg.ChannelName)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, member_name, channel_name FROM roles WHERE id = ? LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}

const getRoleByChannel = `-- name: GetRoleByChannel :many
SELECT id, member_name, channel_name FROM roles WHERE channel_name = ?
`

func (q *Queries) GetRoleByChannel(ctx context.Context, channelName string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoleByChannel, channelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.MemberName, &i.ChannelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByMemberAndChannel = `-- name: GetRoleByMemberAndChannel :one
SELECT id, member_name, channel_name FROM roles WHERE member_name = ? AND channel_name = ? LIMIT 1
`

type GetRoleByMemberAndChannelParams struct {
	MemberName  string `json:"member_name"`
	ChannelName string `json:"channel_name"`
}

func (q *Queries) GetRoleByMemberAndChannel(ctx context.Context, arg GetRoleByMemberAndChannelParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByMemberAndChannel, arg.MemberName, arg.ChannelName)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}

const getRoleByTask = `-- name: GetRoleByTask :one
SELECT r.id, r.member_name, r.channel_name FROM roles r
JOIN tasks d ON d.role_id = r.id
WHERE d.id = ?
LIMIT 1
`

func (q *Queries) GetRoleByTask(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByTask, id)
	var i Role
	err := row.Scan(&i.ID, &i.MemberName, &i.ChannelName)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, member_name, channel_name FROM roles
`

func (q *Queries) GetRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.MemberName, &i.ChannelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
