// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_executions.sql

package entities

import (
	"context"
)

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (execution_id, task_id) VALUES (?, ?) RETURNING execution_id, task_id
`

type CreateTaskExecutionParams struct {
	ExecutionID string `json:"execution_id"`
	TaskID      string `json:"task_id"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, createTaskExecution, arg.ExecutionID, arg.TaskID)
	var i TaskExecution
	err := row.Scan(&i.ExecutionID, &i.TaskID)
	return i, err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT execution_id, task_id FROM task_executions WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetTaskExecution(ctx context.Context, executionID string) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecution, executionID)
	var i TaskExecution
	err := row.Scan(&i.ExecutionID, &i.TaskID)
	return i, err
}

const getTaskExecutions = `-- name: GetTaskExecutions :many
SELECT execution_id, task_id FROM task_executions ORDER BY execution_id ASC
`

func (q *Queries) GetTaskExecutions(ctx context.Context) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, getTaskExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(&i.ExecutionID, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
