// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package entities

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, role_id, prev_id, instruction) VALUES (?, ?, ?, ?) RETURNING id, role_id, prev_id, instruction
`

type CreateTaskParams struct {
	ID          string         `json:"id"`
	RoleID      string         `json:"role_id"`
	PrevID      sql.NullString `json:"prev_id"`
	Instruction string         `json:"instruction"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.RoleID,
		arg.PrevID,
		arg.Instruction,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
	)
	return i, err
}

const getFirstTask = `-- name: GetFirstTask :one
SELECT id, role_id, prev_id, instruction FROM tasks
WHERE role_id = ?
AND prev_id IS NULL
LIMIT 1
`

func (q *Queries) GetFirstTask(ctx context.Context, roleID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getFirstTask, roleID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, role_id, prev_id, instruction FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PrevID,
		&i.Instruction,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, role_id, prev_id, instruction FROM tasks
`

func (q *Queries) GetTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.PrevID,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
