// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_executions.sql

package entities

import (
	"context"
)

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (id, execution_id) VALUES (?, ?) RETURNING id, execution_id
`

type CreateTaskExecutionParams struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, createTaskExecution, arg.ID, arg.ExecutionID)
	var i TaskExecution
	err := row.Scan(&i.ID, &i.ExecutionID)
	return i, err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT id, execution_id FROM task_executions WHERE id = ? LIMIT 1
`

func (q *Queries) GetTaskExecution(ctx context.Context, id string) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecution, id)
	var i TaskExecution
	err := row.Scan(&i.ID, &i.ExecutionID)
	return i, err
}

const getTaskExecutions = `-- name: GetTaskExecutions :many
SELECT id, execution_id FROM task_executions ORDER BY id ASC
`

func (q *Queries) GetTaskExecutions(ctx context.Context) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, getTaskExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(&i.ID, &i.ExecutionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskExecutionsByExecution = `-- name: GetTaskExecutionsByExecution :many
SELECT id, execution_id FROM task_executions WHERE execution_id = ? ORDER BY id ASC
`

func (q *Queries) GetTaskExecutionsByExecution(ctx context.Context, executionID string) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, getTaskExecutionsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(&i.ID, &i.ExecutionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
