// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool.sql

package entities

import (
	"context"
	"encoding/json"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (id, task_id, tool) VALUES (?, ?, ?) RETURNING id, task_id, tool
`

type CreateToolParams struct {
	ID     string          `json:"id"`
	TaskID string          `json:"task_id"`
	Tool   json.RawMessage `json:"tool"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRowContext(ctx, createTool, arg.ID, arg.TaskID, arg.Tool)
	var i Tool
	err := row.Scan(&i.ID, &i.TaskID, &i.Tool)
	return i, err
}

const getToolsByTask = `-- name: GetToolsByTask :many
SELECT id, task_id, tool FROM tools WHERE task_id = ?
`

func (q *Queries) GetToolsByTask(ctx context.Context, taskID string) ([]Tool, error) {
	rows, err := q.db.QueryContext(ctx, getToolsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(&i.ID, &i.TaskID, &i.Tool); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
