// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_action_messages.sql

package entities

import (
	"context"
)

const updateActionMessages = `-- name: UpdateActionMessages :one
UPDATE actions 
SET tool_requirement_message_id = ?, tool_result_message_id = ? 
WHERE id = ? RETURNING id, run_id, step_id, tool_call, tool_requirement_message_id, tool_result_message_id
`

type UpdateActionMessagesParams struct {
	ToolRequirementMessageID interface{} `json:"tool_requirement_message_id"`
	ToolResultMessageID      interface{} `json:"tool_result_message_id"`
	ID                       string      `json:"id"`
}

func (q *Queries) UpdateActionMessages(ctx context.Context, arg UpdateActionMessagesParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, updateActionMessages, arg.ToolRequirementMessageID, arg.ToolResultMessageID, arg.ID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.ToolCall,
		&i.ToolRequirementMessageID,
		&i.ToolResultMessageID,
	)
	return i, err
}
